services:
  ot-br:
    image: openthread/otbr:latest
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.conf.all.forwarding: 1
      net.ipv6.conf.all.forwarding: 1
    volumes:
      - /dev/ttyACM0:/dev/ttyACM0
    ports:
      - 8080:80
    dns:
     - 127.0.0.1
    privileged: true
    command: [ "--radio-url", "spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=115200&uart-flow-control"]
    networks:
      ipv6net:
        ipv6_address: fdbe:8cb7:f64c:1::2

  attacker:
    image: nginx:alpine
    networks:
      ipv6net:
        ipv6_address: fdbe:8cb7:f64c:1::3
    cap_add:
      - NET_ADMIN

networks:
  ipv6net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
      - subnet: fdbe:8cb7:f64c:1::/64
        gateway: fdbe:8cb7:f64c:1::1
