# Compose file for setting up the faucet SDN controller
# as well as the MUD file server and (TODO) the MUD manager
include:
    - path:
        - '../faucet/docker-compose.yaml'
        - './docker/faucet.override.yaml'
    - path:
        - '../mud-manager/docker-compose.yaml'
        - './docker/mud-manager.override.yaml'

services:
    mudfileserver:
        restart: on-failure
        build:
            context: .
            dockerfile: ./docker/Dockerfile.mud_fileserver
        ports:
            - '3001:3000'
        volumes:
            - ./mudfiles:/home/static
        links:
            - mud-manager
