# Compose file for setting up the faucet SDN controller
# as well as the MUD file server and (TODO) the MUD manager
include:
    - path:
        - '../faucet/docker-compose.yaml'
        - 'faucet.override.yaml'
    - path:
        - '../mud-manager/docker-compose.yaml'
        - mud-manager.override.yaml

services:
    mudfileserver:
        build:
            context: .
            dockerfile: Dockerfile.mud_fileserver
        ports:
            - '3001:3000'
        volumes:
            - ./mudfiles:/home/static
        links:
            - mud-manager
