# Compose file for setting up the faucet SDN controller
# as well as the MUD file server and (TODO) the MUD manager
include:
  - '../faucet/docker-compose.yaml'

services:
  mudfileserver:
    build:
      context: .
      dockerfile: Dockerfile.mud_fileserver
    ports:
      - '3001:3000'
    volumes:
      - ./mudfiles:/home/static
    # links:
    #   - faucet