## Image name: mudthreadv2/fileserver
# Inspired by: https://lipanski.com/posts/smallest-docker-image-static-website

FROM busybox:latest

# Create a non-root user to own the files and run our server
RUN adduser -D static
USER static
WORKDIR /home/static

# Run BusyBox httpd
CMD ["busybox", "httpd", "-f", "-v", "-p", "3000"]
