#!/bin/bash

export OMR_PREFIX="fd71:666b:b2e1:bfd9::"
export PREFIX_ROUTE="${OMR_PREFIX}/64"

export BORDER_ROUTER_VLAN="fd99:aaaa:bbbb:100::"
export BORDER_ROUTER_PREFIX_ROUTE="${BORDER_ROUTER_VLAN}/64"
export BORDER_ROUTER_FAUCET_VIP="${BORDER_ROUTER_VLAN}1"
export BORDER_ROUTER_IP="${BORDER_ROUTER_VLAN}2"
export BORDER_ROUTER_SUBNET="${BORDER_ROUTER_IP}/64"

export SERVER_VLAN="fd99:aaaa:bbbb:200::"
export SERVER_PREFIX_ROUTE="${SERVER_VLAN}/64"
export SERVER_FAUCET_VIP="${SERVER_VLAN}1"
export SERVER_IP="${SERVER_VLAN}2"
export SERVER_SUBNET="${SERVER_IP}/64"

export ATTACKER_VLAN="fd99:aaaa:bbbb:300::"
export ATTACKER_PREFIX_ROUTE="${ATTACKER_VLAN}/64"
export ATTACKER_FAUCET_VIP="${ATTACKER_VLAN}1"
export ATTACKER_IP="${ATTACKER_VLAN}2"
export ATTACKER_SUBNET="${ATTACKER_IP}/64"
